In [3]:
import torch

inputs = torch.tensor(
    [[0.43, 0.15, 0.89],  # Your     (x^1)
     [0.55, 0.87, 0.66],  # journey  (x^2)
     [0.57, 0.85, 0.64],  # starts   (x^3)
     [0.22, 0.58, 0.33],  # with     (x^4)
     [0.77, 0.25, 0.10],  # one      (x^5)
     [0.05, 0.80, 0.55]]  # step     (x^6)
)

x_2 = inputs[1]     #1
d_in = inputs.shape[1]      #2
d_out = 2         #3

x_2, d_in, d_out

(tensor([0.5500, 0.8700, 0.6600]), 3, 2)

In [6]:
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key   = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_query, W_key, W_value

(Parameter containing:
 tensor([[0.2961, 0.5166],
         [0.2517, 0.6886],
         [0.0740, 0.8665]]),
 Parameter containing:
 tensor([[0.1366, 0.1025],
         [0.1841, 0.7264],
         [0.3153, 0.6871]]),
 Parameter containing:
 tensor([[0.0756, 0.1966],
         [0.3164, 0.4017],
         [0.1186, 0.8274]]))

In [10]:
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value
print("Query:", query_2)
print("Key:  ", key_2)
print("Value:", value_2)

Query: tensor([0.4306, 1.4551])
Key:   tensor([0.4433, 1.1419])
Value: tensor([0.3951, 1.0037])


In [13]:
keys = inputs @ W_key
values = inputs @ W_value
print("keys.shape:", keys.shape)
print("values.shape:", values.shape)
keys, values

keys.shape: torch.Size([6, 2])
values.shape: torch.Size([6, 2])


(tensor([[0.3669, 0.7646],
         [0.4433, 1.1419],
         [0.4361, 1.1156],
         [0.2408, 0.6706],
         [0.1827, 0.3292],
         [0.3275, 0.9642]]),
 tensor([[0.1855, 0.8812],
         [0.3951, 1.0037],
         [0.3879, 0.9831],
         [0.2393, 0.5493],
         [0.1492, 0.3346],
         [0.3221, 0.7863]]))

In [15]:
keys = inputs @ W_key
values = inputs @ W_value
print("keys.shape:", keys.shape)
print("values.shape:", values.shape)

keys.shape: torch.Size([6, 2])
values.shape: torch.Size([6, 2])


In [18]:
keys_2 = keys[1]             #1
print("Keys[1]:", keys_2)
print("Query[1]:", query_2)
attn_score_22 = query_2.dot(keys_2)
print(attn_score_22)

Keys[1]: tensor([0.4433, 1.1419])
Query[1]: tensor([0.4306, 1.4551])
tensor(1.8524)


In [34]:
print(f"Query: {query_2}")
print(f"Keys:  {keys}")
attn_scores_2 = query_2 @ keys.T       #1
print(attn_scores_2)

Query: tensor([0.4306, 1.4551])
Keys:  tensor([[0.3669, 0.7646],
        [0.4433, 1.1419],
        [0.4361, 1.1156],
        [0.2408, 0.6706],
        [0.1827, 0.3292],
        [0.3275, 0.9642]])
tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])


In [25]:
d_k = keys.shape[-1]
print(d_k)
attn_weights_2 = torch.softmax(attn_scores_2 / (d_k ** 0.5), dim=-1)  #1
attn_weights_2

2


tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])

In [31]:
print(f"Attention weights: {attn_weights_2}")
print(f"Values:            {values}")
context_vec_2 = attn_weights_2 @ values
print(context_vec_2)

Attention weights: tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])
Values:            tensor([[0.1855, 0.8812],
        [0.3951, 1.0037],
        [0.3879, 0.9831],
        [0.2393, 0.5493],
        [0.1492, 0.3346],
        [0.3221, 0.7863]])
tensor([0.3061, 0.8210])


In [33]:
(0.2*0.2 + 0.2*0.4 + 0.2*0.4 + 0.1*0.2 + 0.1*0.1 * 0.2*0.3,
 0.2*0.9 + 0.2*1 + 0.2*1 + 0.1*0.5 + 0.1*0.3 * 0.2*0.8)

(0.22060000000000002, 0.6348000000000001)