In [17]:
import torch
from torch import nn


class BasicNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 1, bias=False)
        self.fc2 = nn.Linear(1, 2, bias=False)

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        return x

In [18]:
torch.manual_seed(123)
model = BasicNeuralNet()
x = torch.tensor([0.5])
output = model(x)
output

tensor([-0.0068,  0.1013], grad_fn=<SqueezeBackward4>)

In [24]:
print("fc1 weight:", model.fc1.weight)
print("fc1 bias:", model.fc1.bias)
print("fc2 weight:", model.fc2.weight)
print("fc2 bias:", model.fc2.bias)

fc1 weight: Parameter containing:
tensor([[-0.4078]], requires_grad=True)
fc1 bias: None
fc2 weight: Parameter containing:
tensor([[ 0.0331],
        [-0.4967]], requires_grad=True)
fc2 bias: None
